### ISSUE TITLE
Tidbegränsning

### ISSUE THREAD

**Issue by sven91swe** [sven91swe/Reversi#1]
Ett system för att begränsa dragens tid bör implementeras.

**Comment by sven91swe** [comment]
Detta kommer att implementeras i Game. /src/Game/Game.java

Finns en metod där som idag ej kontrollerar tid men som skall kontrollera tidsåtgång i framtiden.

**Comment by joel-magnusson** [comment]
Done!

**Comment by sven91swe** [comment]
Så nu har jag fixat så koden fungerar som tänkt. 
10 sekunder sedan tas draget. 2 sekunder till för avslut.

Har även sett till så att det fungerar om det tar mindre än 10 sekunder för draget att bli klart.
