### ISSUE TITLE
Svens Game tror att Svens bot slår min bot.

### ISSUE THREAD

**Issue by joel-magnusson** [sven91swe/Reversi#13]
OldGame och Game ger olika resultat med samma bottar (ExempelBot vs NotABot). I Game ser spelet ut som om det vore mellan 2st ExempelBot. Under debugging verkar så dock inte vara fallet. Har även testat att switcha botarnas färger, men har tyvärr misslyckats med att hitta anledningen till denna avvikelse..

**Comment by sven91swe** [comment]
Efter att ha rättat en sak i Game ger båda samma svar. Vänligen testkör och bekräfta. Du kan jämföra sista ställningen på brädet.

**Comment by joel-magnusson** [comment]
Såg bra ut!
