### ISSUE TITLE
Se tidigare gjorda drag

### ISSUE THREAD

**Issue by sven91swe** [sven91swe/Reversi#20]
Bör board innehålla en lista över tidigare drag?

Det är i detta spel känd information. Men samtidigt kan ju botten räkna ut det. Jag lutar med att ReversiBoard borde innehålla en lista.

**Comment by joel-magnusson** [comment]
Tycker inte det passar in i board. Potentiellt Game eller Logger i så fall.

**Comment by sven91swe** [comment]
Den lades in i Game och blev en separat argument till CalculateNextMove. Om fler saker kommer att läggas till det skulle jag överväga att skriva om hela CalculateNextMove (paketera om input till en som beskriver bräde, tidigare drag samt annat?)
